name: Docs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # ---------------- TESTS ----------------
  gtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ libgtest-dev cmake

      - name: Build gtest (Ubuntu requirement)
        run: |
          cd /usr/src/googletest
          sudo cmake .
          sudo make
          sudo cp lib/libgtest*.a /usr/lib/

      - name: Compile tests
        run: |
          g++ -std=c++17 tests/*.cpp -lgtest -lgtest_main -pthread -I src -o tests_runner

      - name: Run tests
        run: ./tests_runner


  # ---------------- DOCS + DEPLOY ----------------
  deploy:
    needs: gtest
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Required for CLANG_ASSISTED_PARSING
      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y \
            doxygen \
            graphviz \
            make \
            clang \
            libc++-dev \
            libc++abi-dev

      - name: Build documentation
        run: make doc

      # Required by GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
